import React from 'react';
import { StaticImage } from 'gatsby-plugin-image';
import '../style/Project.css';
import Header from '../Components/Header';
import Footer from '../Components/Footer';

function ESNetMRDP() {
  return (
    <>
     <Header />
      <div className="container">
        <div className="header-image">
          <StaticImage 
            src="../../static/ESNetMRDPHeader.png"
            alt="Project Header"
            placeholder="blurred"
            layout="constrained"
            style={{ borderRadius: '10px' }}
          />
        </div>
      
        <div className="info-row">
          <div className="info-item">
            <h3 className="info-title">Role</h3>
            <p className="info-content">UX Engineer Intern</p>
          </div>
          <div className="info-item">
            <h3 className="info-title">Skills</h3>
            <p className="info-content">
              <b>UI Engineering:</b> React Development, Jinja Templating, Django Framework, Ansible, Docker 
              <br />
              <b>UX Redesign:</b> UX Research, UX Interface Mockups, User Flow, Wireframing
            </p>
          </div>
          <div className="info-item">
            <h3 className="info-title">Timeline</h3>
            <p className="info-content">
              June 2024 - August 2024
            </p>
          </div>
          <div className="info-item">
            <h3 className="info-title">Team</h3>
            <p className="info-content">
            Johanna Lee
            <br />
            James Kafader (Supervisor)
            <br />
            Ken Miller (Client Point of Contact)
            </p>
          </div>
          
        </div>

        <div className="section">
          <h2 className="section-title">Background</h2>
          <div className="flex-container">
            <div className="subsection">
              <h3 className="subsection-title">Energy Science Network</h3>
              <p className="paragraph">
              The <b>Energy Sciences Network</b> is a high-performance network designed to support large-scale scientific research by <b>interconnecting the U.S. 
              Department of Energy's national laboratory system</b>. It facilitates the <b>transfer of massive data sets</b> generated by scientific experiments, enabling 
              collaboration among researchers across various disciplines.
              </p>
            </div>
            <div className="subsection">
              <h3 className="subsection-title">Lawrence Berkeley National Laboratory</h3>
              <p className="paragraph">
              <b>Lawrence Berkeley National Laboratory</b> is a leading research facility located in Berkeley, California, established in 1931 and operated by the 
              University of California. Funded by the <b>U.S. Department of Energy</b>, LBNL focuses on advancing scientific knowledge in areas such as <b>energy efficiency,
               environmental sustainability, and health.</b> 
              </p>
            </div>
          </div>
        </div>

        <div className="section">
          <h2 className="section-title">Project Scope</h2>
          <div className="flex-container">
            <div className="team-photo" style={{ flex: '1', maxWidth: '40%' }}>
              <StaticImage 
              src="../../static/ESNetMRDPScreenshot.png"
              alt="Project Header"
              placeholder="blurred"
              layout="constrained"
              style={{ marginTop: '10px',borderRadius: '2px' }}
              />
              <p className="photoDescription">
              Final Landing Page for Modern Researh Data Portal
              </p>
            </div>
            <div className="subsection" style={{ flex: '1', maxWidth: '60%' }}>
              <h3 className="subsection-title">Modern Research Data Portal</h3>
              <p className="paragraph">
               MRDP streamlines high-speed data transfer by enabling secure, reliable file transfers between 
               authorized Globus source/destination points, browse datasets for transfers and monitor transfer progress. MRDP acceleartes research
              workflows and enhance collaboration by providing a centralized access point to facilitate data transfers.
              </p>
              <h3 className="subsection-title">Goal</h3>
              <p className="paragraph">
              Improving the <b>Modern Research Data Portal (MRDP)</b> through UI/UX redesign and Django-based web development. 
              Aiming to transform the MRDP codebase into a <b>versatile, distributable, and customizable solution for various research institutions</b>.
              </p>
            </div>
          </div>
        </div>
        <div className="section">
          <h2 className="section-title">Reflection</h2>
          <div className="flex-container">

            <div className="subsection" style ={{ maxWidth: '60%' }}>
              <h3 className="subsection-title">User Flow Redesign:</h3>
              <p className="paragraph">
              My project aimed to design for a <b>niche group of lab researchers,</b>. shifting my focus from previous 
              GenZ targeted marketing projects. I aimed to create a UX that prioritized versatility and approachability, 
              leading to a redesign of the website's user flow, which simplified navigation by <b>consolidating two-page operations 
              into a efficient single-page experience</b>.
              </p>

              <h3 className="subsection-title">Distributable and Customizable Codebase Development:</h3>
              <p className="paragraph">
              Another focus was creating templates that <b>future developers could easily customize and distribute</b>, ensuring that my 
              design was both <b>user-friendly for end-users and adaptable for developers</b>. This experience broadened my perspective on user 
              experience design and highlighted the importance of balancing technical requirements with usability.
              </p>
            </div>

            <div className="team-photo" style={{ flex: '1', maxWidth: '40%' }}>
              <StaticImage 
              src="../../static/ESNetMRDPPresentation.jpg"
              alt="Project Header"
              placeholder="blurred"
              layout="constrained"
              style={{ marginTop: '40px', borderRadius: '10px' }}
              />
              <p className="photoDescription">
              Student Poster Session for Berkeley Lab Computing Sciences
              </p>
            </div>

          </div>
        </div>



        

      </div>
    <Footer />
    </>
  );
}

export default ESNetMRDP;