import React, { useEffect, useRef, useState } from 'react';
import { StaticImage } from 'gatsby-plugin-image';
import '../style/Project.css';
import Header from '../Components/Header';
import Footer from '../Components/Footer';

function ESNetMRDP() {
    const imageRefs = useRef([]);
    const [slideIndex, setSlideIndex] = useState(1);
  
  useEffect(() => {
    const setupImageZoom = (container) => {
      if (!container) return;
  
      const image = container.querySelector('.slidepng');
      
      const handleMouseMove = (e) => {
        const { left, top, width, height } = container.getBoundingClientRect();
        const x = (e.clientX - left) / width;
        const y = (e.clientY - top) / height;
  
        image.style.transformOrigin = `${x * 100}% ${y * 100}%`;
        image.style.transform = 'scale(1.5)';
      };
  
      const handleMouseLeave = () => {
        image.style.transformOrigin = 'center center';
        image.style.transform = 'scale(1)';
      };
  
      container.addEventListener('mousemove', handleMouseMove);
      container.addEventListener('mouseleave', handleMouseLeave);
  
      return () => {
        container.removeEventListener('mousemove', handleMouseMove);
        container.removeEventListener('mouseleave', handleMouseLeave);
      };
    };
  
    const cleanupFunctions = imageRefs.current.map(container => setupImageZoom(container));
  
    return () => {
      cleanupFunctions.forEach(cleanup => cleanup && cleanup());
    };
  }, []);

  const changeSlide = (n) => {
    setSlideIndex(prevIndex => {
        let newIndex = prevIndex + n;
        const slides = document.getElementsByClassName("slide");
        if (newIndex > slides.length) newIndex = 1;
        if (newIndex < 1) newIndex = slides.length;
        return newIndex;
    });
};

useEffect(() => {
    const slides = document.getElementsByClassName("slide");
    for (let i = 0; i < slides.length; i++) {
        slides[i].style.display = "none";
    }
    if (slides[slideIndex - 1]) {
        slides[slideIndex - 1].style.display = "block";
    }
}, [slideIndex]);

  return (
    <>
     <Header />
      <div className="container">
        <div className="header-image">
          <StaticImage 
            src="../../static/ESNetMRDPHeader.png"
            alt="Project Header"
            placeholder="blurred"
            layout="constrained"
            style={{ borderRadius: '10px' }}
          />
        </div>
      
        <div className="info-row">
          <div className="info-item">
            <h3 className="info-title">Role</h3>
            <p className="info-content">UX Engineer Intern</p>
          </div>
          <div className="info-item">
            <h3 className="info-title">Skills</h3>
            <p className="info-content">
              <b>UI Engineering:</b> 
              <br/>React Development, Jinja Templating, Django Framework, Ansible, Docker 
              <br />
              <b>UX Redesign:</b> <br/>UX Research, UX Interface Mockups, User Flow, Wireframing
            </p>
          </div>
          <div className="info-item">
            <h3 className="info-title">Timeline</h3>
            <p className="info-content">
              June 2024 - August 2024
            </p>
          </div>
          <div className="info-item">
            <h3 className="info-title">Team</h3>
            <p className="info-content">
            Johanna Lee
            <br />
            James Kafader (Supervisor)
            <br />
            Ken Miller (Client Point of Contact)
            </p>
          </div>
        </div>

        <div className="section">
          <h2 className="section-title">Problem Space</h2>
          <div className="flex-container">
            <div className="subsection">
              <h3 className="subsection-title" style={{ color: '#50C5DB' }}>Energy Science Network</h3>
              <p className="paragraph">
              Energy Sciences Network is a <b>high-performance network</b> designed to support large-scale scientific research by <b>interconnecting the U.S. 
              Department of Energy's national laboratory system</b>. 
              </p>
              <p className="paragraph">
              It facilitates the transfer of massive data sets generated by scientific experiments, enabling 
              collaboration among researchers across various disciplines.
              </p>
            </div>

            <div className="subsection">
              <h3 className="subsection-title" style={{ color: '#50C5DB' }}>Modern Research Data Portal</h3>
              <p className="paragraph">
                MRDP streamlines high-speed data transfer process by:
              </p>
              <p className="paragraph">
              <ul className="bullet-list">
                <li>Enables fast and reliable file transfers between <b>authorized Globus points.</b></li>
                <li>Provides a <b>single portal</b> for initiating transfers, browsing datasets, and monitoring progress.</li>
                <li>Accelerates research workflows, facilitating <b>efficient data movement</b> and collaboration among researchers.</li>
              </ul>
              </p>

              <h3 className="subsection-title" style={{ color: '#50C5DB' }}>Problem</h3>
              <p className="paragraph">
              During the internship, I worked on improving the Modern Research Data Portal (MRDP) through UI/UX redesign and Django-based web development. 
              I was assigned to transform the MRDP into a <b>versatile, distributable, and customizable codebase solution</b> for various research institutions.
              </p>


              <div className="subsection">
                <h3 className="subsection-title" style={{ color: '#0075A2', background: '#ffffff', borderRadius: '30px', padding: '20px', textAlign: 'center'}}>
                How might we reimagine the Modern Research Data Portal to create an intuitive, streamlined experience that empowers research institutions to effortlessly manage and share their data?
                </h3>
              </div>

            </div>
            
          </div>
        </div>

        <div className="section">
          <h2 className="section-title">UX Research</h2>
          <div className="flex-container">
          <div className="subsection">
            <h3 className="subsection-title" style={{ color: '#50C5DB' }}>UX Audit</h3>
                <p className="paragraph">
                During the internship, I worked on improving the Modern Research Data Portal (MRDP) through UI/UX redesign and Django-based web development. 
                I was assigned to transform the MRDP into a <b>versatile, distributable, and customizable codebase solution</b> for various research institutions.
                </p>


                <div className="slideshow-container">
                                <div className="slide fade">
                                    <StaticImage src="../../static/esnetmrdp/mrdpOG1.png" alt="Slide 1" />
                                </div>
                                <div className="slide fade">
                                    <StaticImage src="../../static/esnetmrdp/mrdpOG2.png" alt="Slide 2" />
                                </div>
                                <div className="slide fade">
                                    <StaticImage src="../../static/esnetmrdp/mrdpOG3.png" alt="Slide 3" />
                                </div>
                                
                                <a className="prev" onClick={() => changeSlide(-1)}>&#10094;</a>
                                <a className="next" onClick={() => changeSlide(1)}>&#10095;</a>
                            </div>

            <div className="slidepng-container">
                        <div className="team-photo" ref={el => imageRefs.current.push(el)}>
                          <StaticImage
                            src="../../static/esnetmrdp/esnetaudit.png"
                            alt="Project Header"
                            placeholder="blurred"
                            layout="constrained"
                            className="slidepng"
                          />
            </div>
            </div>





            <div className="slidepng-container">
                        <div className="team-photo" ref={el => imageRefs.current.push(el)}>
                          <StaticImage
                            src="../../static/esnetmrdp/mrdpOG1.png"
                            alt="Project Header"
                            placeholder="blurred"
                            layout="constrained"
                            className="slidepng"
                          />
            </div>
            </div>

            <div className="slidepng-container">
                        <div className="team-photo" ref={el => imageRefs.current.push(el)}>
                          <StaticImage
                            src="../../static/esnetmrdp/mrdpOG2.png"
                            alt="Project Header"
                            placeholder="blurred"
                            layout="constrained"
                            className="slidepng"
                          />
            </div>
            </div>

            <div className="slidepng-container">
                        <div className="team-photo" ref={el => imageRefs.current.push(el)}>
                          <StaticImage
                            src="../../static/esnetmrdp/mrdpOG3.png"
                            alt="Project Header"
                            placeholder="blurred"
                            layout="constrained"
                            className="slidepng"
                          />
            </div>
            </div>

            


            </div>
          </div>
        </div>






        <div className="section">
          <h2 className="section-title">Reflection</h2>
          <div className="flex-container">
              <div className="team-photo">
                  <StaticImage 
                  src="../../static/ESNetMRDPScreenshot.png"
                  alt="Project Header"
                  placeholder="blurred"
                  layout="constrained"
                  style={{ marginTop: '10px',borderRadius: '10px' }}
                  />
                  <p className="photoDescription">
                  Final Landing Page for Modern Researh Data Portal
                  </p>
                </div>

            <div className="subsection">
              <h3 className="subsection-title" style={{ color: '#50C5DB' }}>User Flow Redesign:</h3>
              <p className="paragraph">
              My project aimed to design for a <b>niche group of lab researchers,</b>. shifting my focus from previous 
              GenZ targeted marketing projects. I aimed to create a UX that prioritized versatility and approachability, 
              leading to a redesign of the website's user flow, which simplified navigation by <b>consolidating two-page operations 
              into a efficient single-page experience</b>.
              </p>

              <h3 className="subsection-title" style={{ color: '#50C5DB' }}>Distributable and Customizable Codebase Development:</h3>
              <p className="paragraph">
              Another focus was creating templates that <b>future developers could easily customize and distribute</b>, ensuring that my 
              design was both <b>user-friendly for end-users and adaptable for developers</b>. This experience broadened my perspective on user 
              experience design and highlighted the importance of balancing technical requirements with usability.
              </p>
            </div>

            <div className="team-photo">
              <StaticImage 
              src="../../static/ESNetMRDPPresentation.jpg"
              alt="Project Header"
              placeholder="blurred"
              layout="constrained"
              style={{ marginTop: '40px', borderRadius: '10px' }}
              />
              <p className="photoDescription">
              Student Poster Session for Berkeley Lab Computing Sciences - Presenting to ESNet Executive Director Inder Monga
              </p>
            </div>

          </div>
        </div>



        

      </div>
    <Footer />
    </>
  );
}

export default ESNetMRDP;